-- Set primary key on tables that are missing a primary key.

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_TYPE = 'PRIMARY KEY' AND TABLE_NAME = 'uCommerce_AppSystemVersion' AND TABLE_SCHEMA ='dbo') 
BEGIN
	ALTER TABLE [dbo].[uCommerce_AppSystemVersion] 
	ADD CONSTRAINT [PK_uCommerce_AppSystemVersion] PRIMARY KEY CLUSTERED ( [AppSystemVersionId] ASC) 
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'uCommerce_SystemVersionSitecore' AND TABLE_SCHEMA = 'dbo')
BEGIN
	IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_TYPE = 'PRIMARY KEY' AND TABLE_NAME = 'uCommerce_SystemVersionSitecore' AND TABLE_SCHEMA ='dbo') 
	BEGIN
		ALTER TABLE [dbo].[uCommerce_SystemVersionSitecore] 
		ADD CONSTRAINT [PK_uCommerce_SystemVersionSitecore] PRIMARY KEY CLUSTERED ( [SystemVersionSitecoreId] ASC)	
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
	END
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'uCommerce_SharedField' AND TABLE_SCHEMA = 'dbo')
BEGIN
	IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_TYPE = 'PRIMARY KEY' AND TABLE_NAME = 'uCommerce_SharedField' AND TABLE_SCHEMA ='dbo') 
	BEGIN
		ALTER TABLE [dbo].[uCommerce_SharedField] 
		ADD CONSTRAINT [PK_uCommerce_SharedField] PRIMARY KEY CLUSTERED ( [SharedFieldId] ASC) 
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
	END
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'uCommerce_UnversionedField' AND TABLE_SCHEMA = 'dbo')
BEGIN 
	IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_TYPE = 'PRIMARY KEY' AND TABLE_NAME = 'uCommerce_UnversionedField' AND TABLE_SCHEMA ='dbo') 
	BEGIN
		ALTER TABLE [dbo].[uCommerce_UnversionedField] 
		ADD CONSTRAINT [PK_uCommerce_UnversionedField] PRIMARY KEY CLUSTERED ( [UnversionedFieldId] ASC) 
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
	END
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'uCommerce_VersionedField' AND TABLE_SCHEMA = 'dbo')
BEGIN
	IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_TYPE = 'PRIMARY KEY' AND TABLE_NAME = 'uCommerce_VersionedField' AND TABLE_SCHEMA ='dbo') 
	BEGIN
		ALTER TABLE [dbo].[uCommerce_VersionedField] 
		ADD CONSTRAINT [PK_uCommerce_VersionedField] PRIMARY KEY CLUSTERED ( [VersionedFieldId] ASC) 
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
	END
END